.TH "ASNOW" "1" "Version 0\&.0\&.1" "Dec 2018"
.PP 
.SH "NAME" 
asnow
.PP 
.SH "SYNOPSIS" 
\fBasnow\fP
[\fB\-x, \-\-xxx\fP \fIsomething\fP]
\fImessage\fP
.PP 
.SH "DESCRIPTION" 
\fBasnow\fP is highly accurate simulation of atmospheric precipitation of
ice crystals (ordinarily known as "snow")\&. Snowflakes can have a variety
of shapes and are represented by ASCII characters, and may melt from time
to time\&.
.PP 
.SH "OPTIONS" 
.IP "\fB\-x, \-\-xxx\fP \fIsomething\fP" 
Explain this option\&.
.PP
.SH "INTERACTIVE COMMANDS" 
None so far\&.
.PP 
.SH "AUTHORS" 
Rudá Moura and Claudio Matsuoka\&.
.PP 
